[backend]
  type = "semtech_udp"

  [backend.semtech_udp]
    udp_bind             = "0.0.0.0:1700"
    skip_crc_check       = false
    fake_rx_time         = false

[integration]
  marshaler = "protobuf"

  [integration.mqtt]
    event_topic_template   = "as923/gateway/{{ .GatewayID }}/event/{{ .EventType }}"
    state_topic_template   = "as923/gateway/{{ .GatewayID }}/state/{{ .StateType }}"
    command_topic_template = "as923/gateway/{{ .GatewayID }}/command/#"
    keep_alive             = "30s"
    max_reconnect_interval = "1m0s"

    [integration.mqtt.auth]
      type = "generic"

      [integration.mqtt.auth.generic]
        server        = "tcp://mosquitto:1883"
        clean_session = false

[metrics]
  type = "prometheus"
  [metrics.prometheus]
    bind = "0.0.0.0:2112"
